
[package]
name = "did-scid"
version = "0.1.2"
description = "Implementation of did:scid in Rust"
repository.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
keywords.workspace = true
publish.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true

[features]
default = ["did-webvh", "did-cheqd"]

did-cheqd = ["dep:did-resolver-cheqd"]
did-webvh = ["dep:didwebvh-rs"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
affinidi-did-common.workspace = true

didwebvh-rs = { version = "0.1", optional = true }
did-resolver-cheqd = { version = "1.0.1", optional = true }
regex = "1.12"
serde_json = "1.0"
ssi-dids-core = "0.1.3"
thiserror = "2.0"
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1.49", features = ["full"] }
